name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Executa o deploy quando há push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use a versão necessária do Node.js

    - name: Install dependencies
      run: npm install

    - name: Zip Lambda function
      run: zip -r function.zip .

    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-cli-action@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Ajuste para a sua região
        run: |
          aws lambda update-function-code --function-name nome-da-sua-lambda --zip-file fileb://function.zip
