name: Testes com Lambda

on:
  push:
    branches:
      - main  # Executa o deploy quando há push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checando Repo
      uses: actions/checkout@v3

    - name: Set up do Node
      uses: actions/setup-node@v3
      with:
        node-version: '20' 

    - name: NPM
      run: npm install

    - name: AWS Teste
      run: aws help

    - name: Zip Lambda function
      run: zip -r function.zip .

    - name: Configurando as credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: "ASIAWOWQJN7MBGVNOXYI"
        aws-secret-access-key: "i4R8DH3D4YTKqHFULhGFCERMsYTLP7tEZ7ldkqm3"
        aws-region: us-east-1  

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name lambda-fiap --zip-file file:"C:\Users\Rafael Paes\Documents\FIAP\lambda-fiaptrust-policy.json"
